site_name: Guido Gagliardi
site_url: https://guidogagl.github.io/physioex/

nav:
  - Home: index.md
  - Research: publications.md
  - Advised Thesis: thesis.md
  - CV: cv.md
theme:
  name: material
  favicon: fontawesome/solid/terminal
  icon: 
    logo: fontawesome/solid/terminal
  features:
    - navigation.tabs
    - navigation.path
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: indigo
      accent: indigo 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: indigo
      accent: light-blue

plugins:
  - search
  - social
  - macros
  
repo_name: guidogagl
repo_url: https://github.com/guidogagl

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/guidogagl
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/guido-gagliardi-5764b6121/
    - icon: fontawesome/brands/orcid
      link: https://orcid.org/0000-0003-2020-6439
    - icon: fontawesome/brands/google-scholar
      link: https://scholar.google.com/citations?view_op=list_works&hl=it&user=8EczeSIAAAAJ
  footer:
    - image: assets/images/avatar.png
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.pathconverter:
      base_path: 'guidogagl.github.io'
      relative_path: '' 
      absolute: true 
      tags: 'a script img link object embed'

copyright: |
  &copy; 2023 <a href="https://github.com/guidogagl"  target="_blank" rel="noopener">Guido Gagliardi</a>